import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "../lib/AuthContext";
import Sidebar from "../components/Sidebar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <div className="app-container">
            <Sidebar />
            <main className="main-content">
              {children}
            </main>
          </div>
        </AuthProvider>
        <style dangerouslySetInnerHTML={{
          __html: `
          .app-container {
            display: flex;
          }
          .main-content {
            flex: 1;
            transition: padding-left 0.3s ease;
          }
          body {
            --sidebar-width: 250px;
          }
          body:has(.sidebar.collapsed) {
            --sidebar-width: 80px;
          }
          .main-content {
            padding-left: var(--sidebar-width);
          }
          @media (max-width: 768px) {
            .main-content {
              padding-left: 0;
            }
          }
        `}} />
      </body>
    </html>
  );
}
